### ISSUE TITLE
ImportError: dynamic module does not define init function (PyInit__tuttle)

### ISSUE THREAD

**Issue by cbenhagen** [buttleofx/ButtleOFX#104]
```
python3 buttleApp.py
Traceback (most recent call last):
  File "buttleApp.py", line 12, in <module>
    import buttleofx
  File "/Users/ben/Projects/ButtleOFX/buttleofx/__init__.py", line 1, in <module>
    from .main import ButtleApp
  File "/Users/ben/Projects/ButtleOFX/buttleofx/main.py", line 20, in <module>
    from pyTuttle import tuttle
  File "/usr/local/Cellar/tuttleofx/0.9.0-dev/python/pyTuttle/tuttle.py", line 32, in <module>
    _tuttle = swig_import_helper()
  File "/usr/local/Cellar/tuttleofx/0.9.0-dev/python/pyTuttle/tuttle.py", line 28, in swig_import_helper
    _mod = imp.load_module('_tuttle', fp, pathname, description)
  File "/usr/local/Cellar/python3/3.4.1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: dynamic module does not define init function (PyInit__tuttle)
```

My system:

```
OSX 10.9.3
Python 3.4.1
PyQt 5.3
TuttleOFX 0.9.0-dev
```

```
echo $TUTTLEOFX_BIN $PYTHONPATH $OFX_PLUGIN_PATH
/usr/local/Cellar/tuttleofx/0.9.0-dev /usr/local/Cellar/tuttleofx/0.9.0-dev/python /usr/local/Cellar/tuttleofx/0.9.0-dev/plugin
```

**Comment by fcastan** [comment]
Could you try to import tuttle in python outside of buttle?

/usr/local/Cellar/python3/3.4.1/Frameworks/Python.framework/Versions/3.4/bin/python3.4
"
from pyTuttle import tuttle
"

**Comment by cbenhagen** [comment]
same:

```
python3
Python 3.4.1 (default, May 19 2014, 13:10:29)
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyTuttle import tuttle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/tuttleofx/0.9.0-dev/python/pyTuttle/tuttle.py", line 32, in <module>
    _tuttle = swig_import_helper()
  File "/usr/local/Cellar/tuttleofx/0.9.0-dev/python/pyTuttle/tuttle.py", line 28, in swig_import_helper
    _mod = imp.load_module('_tuttle', fp, pathname, description)
  File "/usr/local/Cellar/python3/3.4.1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: dynamic module does not define init function (PyInit__tuttle)
```
