### ISSUE TITLE
Fix errors at start

### ISSUE THREAD

**Issue by mfe** [buttleofx/ButtleOFX#66]
Errors : 

`IndexError: list index out of range`
`TypeError: Cannot read property 'fileSize' of undefined` 

Full stack trace :

`Traceback (most recent call last):
  File "/datas/mfe/workspace_ButtleOFX/ButtleOFX/QuickMamba/quickmamba/models/listmodel.py", line 211, in get
    return self._objects[i]
IndexError: list index out of range
Traceback (most recent call last):
  File "/datas/mfe/workspace_ButtleOFX/ButtleOFX/QuickMamba/quickmamba/models/listmodel.py", line 211, in get
    return self._objects[i]
IndexError: list index out of range
Traceback (most recent call last):
  File "/datas/mfe/workspace_ButtleOFX/ButtleOFX/QuickMamba/quickmamba/models/listmodel.py", line 211, in get
    return self._objects[i]
IndexError: list index out of range
Traceback (most recent call last):
  File "/datas/mfe/workspace_ButtleOFX/ButtleOFX/QuickMamba/quickmamba/models/listmodel.py", line 211, in get
    return self._objects[i]
IndexError: list index out of range
file:////datas/mfe/workspace_ButtleOFX/ButtleOFX/buttleofx/MainWindow.qml:17:1: QML MainWindow: Binding loop detected for property "selectedView"
file:////datas/mfe/workspace_ButtleOFX/ButtleOFX/buttleofx/MainWindow.qml:17:1: QML MainWindow: Binding loop detected for property "selectedView"
file:////datas/mfe/workspace_ButtleOFX/ButtleOFX/buttleofx/MainWindow.qml:17:1: QML MainWindow: Binding loop detected for property "selectedView"
file:////datas/mfe/workspace_ButtleOFX/ButtleOFX/buttleofx/MainWindow.qml:39: Error: no such table: settings Unable to execute statement
file:////datas/mfe/workspace_ButtleOFX/ButtleOFX/buttleofx/gui/browser/qml/FooterBar.qml:27:19: Unable to assign [undefined] to QString
file:////datas/mfe/workspace_ButtleOFX/ButtleOFX/buttleofx/gui/browser/qml/FooterBar.qml:51: TypeError: Cannot read property 'fileSize' of undefined`

**Comment by jon92** [comment]
I've fixed some of them but there is still a last one:
file:////datas/mfe/workspace_ButtleOFX/ButtleOFX/buttleofx/MainWindow.qml:39: Error: no such table: settings Unable to execute statement
